#!/usr/bin/bash
# kvm_post_template
# kvm vm post script template 
# Robert Wang @github.com/robertluwang
# Dec 17, 2018

rm -f /etc/sysconfig/network-scripts/ifcfg-eth*

cat <<EOF > /etc/sysconfig/network-scripts/ifcfg-eth0
DEVICE=eth0
NAME="eth0"
ONBOOT="yes"
BOOTPROTO="none"
TYPE="Ethernet"
IPADDR=_nat_ip_
NETMASK=_nat_mask_
GATEWAY=_nat_if_
DNS1=_nat_if_
DNS2=8.8.8.8
EOF

cat <<EOF > /etc/sysconfig/network-scripts/ifcfg-eth1
DEVICE=eth1
NAME="eth1"
ONBOOT="yes"
BOOTPROTO="none"
TYPE="Ethernet"
IPADDR=_provision_ip_
NETMASK=_provision_mask_
EOF


systemctl restart network
