#!/usr/bin/bash
# kvm_post_template
# kvm vm post script template 
# Robert Wang @github.com/robertluwang
# Dec 17, 2018
# Dec 10, 2022 update NIC name

rm -f /etc/sysconfig/network-scripts/ifcfg-_nic_*

cat <<EOF > /etc/sysconfig/network-scripts/ifcfg-_nic1_
DEVICE=_nic1_
NAME="_nic1_"
ONBOOT="yes"
BOOTPROTO="none"
TYPE="Ethernet"
IPADDR=_nat_ip_
NETMASK=_nat_mask_
GATEWAY=_nat_if_
DNS1=_nat_if_
DNS2=8.8.8.8
EOF

cat <<EOF > /etc/sysconfig/network-scripts/ifcfg-_nic2_
DEVICE=_nic2_
NAME="_nic2_"
ONBOOT="yes"
BOOTPROTO="none"
TYPE="Ethernet"
IPADDR=_provision_ip_
NETMASK=_provision_mask_
EOF

systemctl restart network
